export const ActionTypes={
    SET_PRODUCTS : 'SET_PRODUCTS',
    SELECTED_PRODUCTS : 'SELECTED_PRODUCTS',
    REMOVE_SELECTED_PRODUCTS : 'REMOVE_SELECTED_PRODUCTS' ,
    Add_TO_CART:'Add_TO_CART',
    REMOVE_FROM_CART:'REMOVE_FROM_CART',
    INCREMENT_ITEM_COUNT :'INCREMENT_ITEM_COUNT',
    DECREMENT_ITEM_COUNT : 'DECREMENT_ITEM_COUNT',
    LOAD_CART_FROM_STORAGE : 'LOAD_CART_FROM_STORAGE',

}
// Action Types
